name:           Meio Virtual Keyboard

author:         fabiomcosta@gmail.com
current:        0.1
category:       Interface
tags:           [keyboard, accessibility]
#docs:          http://url_to_docs
#demo:          http://demo_url
#requires:
#  - { package: 'some-plugin', version: '0.1' }
#  - { package: 'http://external-plugin.com' }
